### ISSUE TITLE
version 9.0.0 : error importing LocalBroadcastManager

### ISSUE THREAD

**Issue by biodiv** [chemerisuk/cordova-plugin-firebase-messaging#260]
Since release 9.0.0 I get the following:

`FirebaseMessagingPluginService.java` tries to import import `androidx.localbroadcastmanager.content.LocalBroadcastManager;` which doesnt exist.

This has been mentioned and fixed in earlier releases: [#80](https://github.com/chemerisuk/cordova-plugin-firebase-messaging/issues/80)

It works with 8.0.1.

Traceback:
```
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

.../platforms/android/app/src/main/java/by/chemerisuk/cordova/firebase/FirebaseMessagingPluginService.java:18: error: package androidx.localbroadcastmanager.content does not exist
import androidx.localbroadcastmanager.content.LocalBroadcastManager;
                                              ^

.../platforms/android/app/src/main/java/by/chemerisuk/cordova/firebase/FirebaseMessagingPluginService.java:37: error: cannot find symbol
    private LocalBroadcastManager broadcastManager;
            ^
  symbol:   class LocalBroadcastManager
  location: class FirebaseMessagingPluginService

.../platforms/android/app/src/main/java/by/chemerisuk/cordova/firebase/FirebaseMessagingPluginService.java:45: error: cannot find symbol
    broadcastManager = LocalBroadcastManager.getInstance(this);
                        ^
  symbol:   variable LocalBroadcastManager
  location: class FirebaseMessagingPluginService

```

**Comment by chemerisuk** [comment]
@biodiv have you tried to add `<preference name="AndroidXEnabled" value="true" />` into `<platform name="android">`?

**Comment by chemerisuk** [comment]
Fix published in v9.0.1

**Comment by biodiv** [comment]
9.0.1 works great, thanks!
